const paragraphs = [
    "Anaximander was a pre-Socratic Greek philosopher who is widely referred to as the father of astronomy and even as the father of cosmology as a result of his works to explain the origin and makeup of the physical universe. He is regarded as the most important of the Ionian philosophers, and was a pupil of Thales. Traditionally, details of his life and opinions are perpetuated not only by Aristotle and Theophrastos, but also by a great number of secondary authors.[9] He lived throughout the fifth and fourth centuries, BCE, and was most likely the first philosopher to try to rationalize the system of the Earth, Sun, and Moon by the use of geometry and mathematics. Anaximander was also said to have created the first map of the world, however, like much of the rest of his works, this has been lost since his time. There is, however, documentation of Anaximander being responsible for the conception of the first mechanical model of the world, which is outlined by a geocentric model. He postulated that the Earth was at the center of the universe, and that its shape was convex and cylindrical, with life existing on one of the two flat sides. Beyond the Earth, sits the other planets, which Anaximander also details the order of. Next are the fixed stars, which he regarded as wheel-like condensations of air filled with fire, provided at certain places with openings through which flames are discharged.[9] Anaximander places the Moon beyond these stars, and assumed it to also be wheel-like in shape, being nineteen times the size of Earth. Finally, on the top of the universe is the Sun, which interacts with the Moon, and the relationship between them is described in terms of aperture, in which a stoppage in would lead to eclipses.",


    "A star is an astronomical object comprising a luminous spheroid of plasma held together by self-gravity. The nearest star to Earth is the Sun. Many other stars are visible to the naked eye at night; their immense distances from Earth make them appear as fixed points of light. The most prominent stars have been categorised into constellations and asterisms, and many of the brightest stars have proper names. Astronomers have assembled star catalogues that identify the known stars and provide standardized stellar designations. The observable universe contains an estimated 1022 to 1024 stars. Only about 4,000 of these stars are visible to the naked eye—all within the Milky Way galaxy.",
    

    "The lunar surface is covered in lunar dust and marked by mountains, impact craters, their ejecta, ray-like streaks and, mostly on the near side of the Moon, by dark maria seas which are plains of cooled magma. These maria formed when large impacts on the far side of the Moon heated up low lying layers of its crust on the near side. The Moon is, beside when passing through Earth's shadow during a lunar eclipse, always illuminated by the Sun, but from Earth the visible illumination shifts during its orbit, producing the lunar phases. The Moon is the brightest celestial object in Earth's night sky. This is mainly due to its large angular diameter, while the reflectance of the lunar surface is comparable to that of asphalt. The apparent size is nearly the same as that of the Sun, allowing it to cover the Sun almost completely during a total solar eclipse. From Earth about  of the lunar surface is visible over time due to cyclical shifts in perspective making parts of the far side of the Moon visible.",


    "Every second, the Sun's core fuses about  million tons of hydrogen into helium, and in the process converts  million tons of matter into energy. This energy, which can take between and years to escape the core, is the source of the Sun's light and heat. Far in the future, when hydrogen fusion in the Sun's core diminishes to the point where the Sun is no longer in hydrostatic equilibrium, its core will undergo a marked increase in density and temperature which will push its outer layers to expand, eventually transforming the Sun into a red giant. This process will make the Sun large enough to render Earth uninhabitable approximately five billion years from the present. After this, the Sun will shed its outer layers and become a dense type of cooling star (a white dwarf), and no longer produce energy by fusion, but still glow and give off heat from its previous fusion for trillions of years. After that it might become a super dense hypothetical black dwarf, giving off no more energy.",


    "A school is both the educational institution and building designed to provide learning spaces and learning environments for the teaching of students under the direction of teachers. Most countries have systems of formal education, which is sometimes compulsory.[2] In these systems, students progress through a series of schools that can be built and operated by both government and private organization. The names for these schools vary by country (discussed in the Regional terms section below) but generally include primary school for young children and secondary school for teenagers who have completed primary education. An institution where higher education is taught is commonly called a university college or university.", 
    
    "Canada is a country in North America. Its ten provinces and three territories extend from the Atlantic Ocean to the Pacific Ocean and northward into the Arctic Ocean, making it the world's second-largest country by total area, with the world's longest coastline. Its border with the United States is the world's longest international land border. The country is characterized by a wide range of both meteorologic and geological regions. It is a sparsely inhabited country of 40 million people, the vast majority residing south of the 55th parallel in urban areas. Canada's capital is Ottawa and its three largest metropolitan areas are Toronto, Montreal, and Vancouver.",


    "Although humans have been storing, retrieving, manipulating, and communicating information since the earliest writing systems were developed, the term information technology in its modern sense first appeared in a  article published in the Harvard Business Review; authors Harold  Leavitt and Thomas L. Whisler commented that the new technology does not yet have a single established name. We shall call it information technology it Their definition consists of three categories: techniques for processing, the application of statistical and mathematical methods to decision-making, and the simulation of higher-order thinking through computer programs",


    "The flag of our country is a symbol of the sovereignty of the Republic. The national flag of the Republic represents the country internationally when official delegations from Uzbekistan visit foreign countries, as well as at conferences, world exhibition, and sports competitions. There are twelve stars, which stand for spiritual sign. The stars also signify the historical traditions of the Uzbek people, as well as ancient solar calendar. A particular attention to twelve stars in the flag is explained yet by another suggestion, that in the states previously existed in the territory of modern Uzbekistan the scientific thought as Astrology had seen its rise. The stars in the Uzbek flag also point to the ancient roots of local culture, the aspirations of Uzbek people towards perfection and loyalty.",
    
    
    "Tashkent, capital of Uzbekistan and the largest city in Central Asia. Tashkent lies in the northeastern part of the country. It is situated at an elevation of 1, to feet in the Chirchiq River valley west of the Chatkal Mountains and is intersected by a series of canals from the Chirchiq River. The city probably dates from the second or the century  and was variously known as Dzhadzh, Chachkent, Shashkent, and Binkent; the name Tashkent, which means “Stone Village” in Uzbek, was first mentioned in the  century. An important centre of trade and handicrafts on the caravan routes to Europe and East Asia, the city was conquered by the Arabs at the beginning of the 8th century and later became part of the possessions of various Muslim ruling lines before falling to the Mongols in the early 13th century. It was subsequently ruled by the Timurids and Shaybānids and then led an independent existence before being annexed by the khanate of Kokand in 1809. When it was captured by the Russians in 1865, it was a walled city of some inhabitants and already a leading centre of trade with Russia. In  it was made the administrative centre of the new governorate-general of Turkistan, and a new European city grew up beside the old native one. Soviet rule was established by Russian colonists in November  after an armed uprising. Tashkent remained the capital of the new republic of Turkistan in the U.S.S.R., but when the latter was split in 1924, Samarkand became the first capital of the republic of Uzbekistan, U.S.S.R. The capital was transferred to Tashkent in 1930.",


    "Asia shares the landmass of Eurasia with Europe, and of Afro-Eurasia with both Europe and Africa. In general terms, it is bounded on the east by the Pacific Ocean, on the south by the Indian Ocean, and on the north by the Arctic Ocean. The border of Asia with Europe is a historical and cultural construct, as there is no clear physical and geographical separation between them. It is somewhat arbitrary and has moved since its first conception in classical antiquity. The division of Eurasia into two continents reflects East–West cultural, linguistic, and ethnic differences, some of which vary on a spectrum rather than with a sharp dividing line. A commonly accepted division places Asia to the east of the Suez Canal separating it from Africa; and to the east of the Turkish Straits, the Ural Mountains and Ural River, and to the south of the Caucasus Mountains and the Caspian and Black seas, separating it from Europe",

    
    "The European Union and the Council of Europe are two important international organisations aiming to represent the European continent on a political level. The Council of Europe was founded in 1948 with the idea of unifying Europe to achieve common goals and prevent future wars. Further European integration by some states led to the formation of the European Union, a separate supranational political entity based on a system of European law that lies between a confederation and a federation. The EU originated in Western Europe but has been expanding eastward since the fall of the Soviet Union in 1991. A majority of its members have adopted a common currency, the euro, and participate in the European single market and a customs union. A large bloc of countries, the Schengen Area, have also abolished internal border and immigration controls. Regular popular elections take place every five years within the EU; they are considered to be the second-largest democratic elections in the world after India's.",


    "Africa straddles the equator and the prime meridian. It is the only continent to stretch from the northern temperate to the southern temperate zones. The majority of the continent and its countries are in the Northern Hemisphere, with a substantial portion and a number of countries in the Southern Hemisphere. Most of the continent lies in the tropics, except for a large part of Western Sahara, Algeria, Libya and Egypt, the northern tip of Mauritania, and the entire territories of Morocco, Ceuta, Melilla, and Tunisia which in turn are located above the tropic of Cancer, in the northern temperate zone. In the other extreme of the continent, southern Namibia, southern Botswana, great parts of South Africa, the entire territories of Lesotho and Eswatini and the southern tips of Mozambique and Madagascar are located below the tropic of Capricorn, in the southern temperate zone.",


    "The ocean moderates climate and has important roles in the water, carbon, and nitrogen cycles. The surface of water interacts with the atmosphere, exchanging properties such as particles and temperature, as well as currents. Surface currents are the water currents that are produced by the atmosphere's currents and its winds blowing over the surface of the water, producing wind waves, setting up through drag slow but stable circulations of water, as in the case of the ocean sustaining deep-sea ocean currents. Deep-sea currents, known together as the global conveyor belt, carry cold water from near the poles to every ocean and significantly influence Earth's climate. Tides, the generally twice-daily rise and fall of sea levels, are caused by Earth's rotation and the gravitational effects of the Moon and, to a lesser extent, of the Sun. Tides may have a very high range in bays or estuaries. Submarine earthquakes arising from tectonic plate movements under the oceans can lead to destructive tsunamis, as can volcanoes, huge landslides, or the impact of large meteorites.",
];